AWSTemplateFormatVersion: 2010-09-09
Description: Enables an AWS Config rule to check whether the specified tags are present on the AWS resouces or not.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Rule Parameters
      - Parameters:
         - tag1Key
         - tag2Key
         - tag3Key
         - tag4Key
 #   ParameterLabels:
 #     - tag1Key:
 #         default: Tag 1

Parameters:
  tag1Key:
    Type: String
    Description: "Tag that should be present on the resouce"
    Default: ""

  tag2Key:
    Type: String
    Description: "Tag that should be present on the resouce"
    Default: ""

  tag3Key:
    Type: String
    Description: "Tag that should be present on the resouce"
    Default: ""

  tag4Key:
    Type: String
    Description: "Tag that should be present on the resouce"
    Default: ""

Resources:
  CheckForTags:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks whether your resources have the tags that you specify. 
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS
      Scope:
        ComplianceResourceTypes:     
          - AWS::ACM::Certificate
          - AWS::AutoScaling::AutoScalingGroup
          - AWS::CloudFormation::Stack
          - AWS::CodeBuild::Project
          - AWS::DynamoDB::Table
          - AWS::EC2::CustomerGateway
          - AWS::EC2::Instance
          - AWS::EC2::InternetGateway
          - AWS::EC2::NetworkAcl
          - AWS::EC2::NetworkInterface
          - AWS::EC2::RouteTable
          - AWS::EC2::SecurityGroup
          - AWS::EC2::Subnet
          - AWS::EC2::Volume
          - AWS::EC2::VPC
          - AWS::EC2::VPNConnection
          - AWS::EC2::VPNGateway
          - AWS::ElasticLoadBalancing::LoadBalancer
          - AWS::ElasticLoadBalancingV2::LoadBalancer
          - AWS::RDS::DBInstance
          - AWS::RDS::DBSecurityGroup
          - AWS::RDS::DBSnapshot
          - AWS::RDS::DBSubnetGroup
          - AWS::RDS::EventSubscription
          - AWS::Redshift::Cluster
          - AWS::Redshift::ClusterParameterGroup
          - AWS::Redshift::ClusterSecurityGroup
          - AWS::Redshift::ClusterSnapshot
          - AWS::Redshift::ClusterSubnetGroup
          - AWS::S3::Bucket

      InputParameters:
        tag1Key : !Ref tag1Key
        tag2Key : !Ref tag2Key
        tag3Key : !Ref tag3Key
        tag4Key : !Ref tag4Key